# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _AlibabaCloud


class _Monitoring(_AlibabaCloud):
    _type = "monitoring"
    _icon_dir = "resources/alibabacloud/monitoring"


class ApplicationConfigurationManagement(_Monitoring):
    _icon = "application-configuration-management.png"


class ApplicationRealtimeMonitoringService(_Monitoring):
    _icon = "application-realtime-monitoring-service.png"


class CloudMonitor(_Monitoring):
    _icon = "cloud-monitor.png"


# Aliases
