# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _AlibabaCloud


class _Other(_AlibabaCloud):
    _type = "other"
    _icon_dir = "resources/alibabacloud/other"


class ResourceOrchestration(_Other):
    _icon = "resource-orchestration.png"


# Aliases
